[project]
name = "financial-data-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.1.13",
    "python-dotenv>=1.0.1",
    "streamlit>=1.43.2",
    "yfinance>=0.2.54",
]
